FORMAT: 1A
HOST: https://blackpolitico-api-heroku.herokuapp.com/

# Politico API

**POLITICO API** Is a pure Flask REST API app that serves endpoints for political parties,government offices,
petitioning,voting and user login and sign up to be consumed by front end frameworks.

## Offices Collection [/api/v2/offices]

### Gets All Offices [GET]

A User with auth token can view all offices

+ Response 200 (application/json)

        [
            "data":[
                     {
                         "id":1,
                         "name":"office_name",
                         "type":"office_type"                 
                     }
                   ],
            "status" : 200       
        ]

### Create a New Office [POST]

An admin user with admin auth token can create an office 

+ Request (application/json)

        {
            "type": "office_type",
            "name":"office_name"
        }

+ Response 201 (application/json)

    + Headers
    
            Authorization: Bearer Token
            Location: /api/v2/offices

    + Body

            {
              "data":[
                {
                "name":"office_name"
                }
              ],
              "status":201
            }
            
## Parties Collection [/api/v2/parties]

### Gets All Parties [GET]

A User with auth token can view all offices

+ Response 200 (application/json)

        [
            "data":[
                     {
                         "id":1,
                         "name":"office_name",
                         "type":"office_type"                 
                     }
                   ],
            "status" : 200       
        ]

### Create a New Party [POST]

An admin user with admin auth token can create an office 

+ Request (application/json)

        {
            "type": "office_type",
            "name":"office_name"
        }

+ Response 201 (application/json)

    + Headers
    
            Authorization: Bearer Token
            Location: /api/v2/offices

    + Body

            {
              "data":[
                {
                "name":"office_name"
                }
              ],
              "status":201
            }